### ISSUE TITLE
URL 如果带了两个参数就会出现 -w command not found 的现象

### ISSUE THREAD

**Issue by ColorfulCat** [dieforfree/qart4j#4]
如果不带参数的url（http://www.baidu.com/）或者只带了一个(http://www.baidu.com?A=S) 都是可以的，但是带了两个参数就不可以了(http://www.baidu.com?A=S&b=2)，是因为 & 符号的问题吗？

**Comment by ColorfulCat** [comment]
java -jar target/qart4j-1.0.0-jar-with-dependencies.jar -i sample-input.png -o sample-output.png -u http://www.baidu.com?a=1&b=1 -w 256 -h 256 -z 256 -v 16 -q 1 --cw EFFFFFFF -cb EFFF1111

**Comment by dieforfree** [comment]
用双引号把URL引起来。
